// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjn78QvHRBSQahHIAy8hJq-_hC83okbHk',
    appId: '1:756560813499:web:34b832d55071b42786b89e',
    messagingSenderId: '756560813499',
    projectId: 'fir-1-b9937',
    authDomain: 'fir-1-b9937.firebaseapp.com',
    storageBucket: 'fir-1-b9937.appspot.com',
    measurementId: 'G-V7VF3PXXB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-LoO7Lm2RDcRZaTM5mkEsx11COYseT4',
    appId: '1:756560813499:android:3f8b631ff1d626c086b89e',
    messagingSenderId: '756560813499',
    projectId: 'fir-1-b9937',
    storageBucket: 'fir-1-b9937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTc8m2tUCPtWEsAAM9-0crP7KKBxQJT4I',
    appId: '1:756560813499:ios:b0345b486ebf716186b89e',
    messagingSenderId: '756560813499',
    projectId: 'fir-1-b9937',
    storageBucket: 'fir-1-b9937.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTc8m2tUCPtWEsAAM9-0crP7KKBxQJT4I',
    appId: '1:756560813499:ios:b0345b486ebf716186b89e',
    messagingSenderId: '756560813499',
    projectId: 'fir-1-b9937',
    storageBucket: 'fir-1-b9937.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjn78QvHRBSQahHIAy8hJq-_hC83okbHk',
    appId: '1:756560813499:web:ff5750af661400a986b89e',
    messagingSenderId: '756560813499',
    projectId: 'fir-1-b9937',
    authDomain: 'fir-1-b9937.firebaseapp.com',
    storageBucket: 'fir-1-b9937.appspot.com',
    measurementId: 'G-H75HYSRYVX',
  );

}